Fix netplan makefile tabs

diff --git a/netplan-Makefile b/netplan-Makefile
--- a/netplan-Makefile
+++ b/netplan-Makefile
@@ -36,95 +36,95 @@ NOSETESTS3 ?= $(shell which nosetests-3 || which nosetests3 || echo true)
 default: netplan/_features.py generate netplan-dbus dbus/io.netplan.Netplan.service
 
 %.o: src/%.c
-        $(CC) $(BUILDFLAGS) $(CFLAGS) $(LDFLAGS) -c $^ `pkg-config --cflags --libs glib-2.0 gio-2.0 yaml-0.1 uuid`
+	$(CC) $(BUILDFLAGS) $(CFLAGS) $(LDFLAGS) -c $^ `pkg-config --cflags --libs glib-2.0 gio-2.0 yaml-0.1 uuid`
 
 libnetplan.so.$(NETPLAN_SOVER): parse.o util.o validation.o error.o
-        $(CC) -shared -Wl,-soname,libnetplan.so.$(NETPLAN_SOVER) $(BUILDFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ $^ `pkg-config --libs yaml-0.1`
-        ln -snf libnetplan.so.$(NETPLAN_SOVER) libnetplan.so
+	$(CC) -shared -Wl,-soname,libnetplan.so.$(NETPLAN_SOVER) $(BUILDFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ $^ `pkg-config --libs yaml-0.1`
+	ln -snf libnetplan.so.$(NETPLAN_SOVER) libnetplan.so
 
 #generate: src/generate.[hc] src/parse.[hc] src/util.[hc] src/networkd.[hc] src/nm.[hc] src/validation.[hc] src/error.[hc]
 generate: libnetplan.so.$(NETPLAN_SOVER) nm.o networkd.o generate.o
-        $(CC) $(BUILDFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ $^ -L. -lnetplan `pkg-config --cflags --libs glib-2.0 gio-2.0 yaml-0.1 uuid`
+	$(CC) $(BUILDFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ $^ -L. -lnetplan `pkg-config --cflags --libs glib-2.0 gio-2.0 yaml-0.1 uuid`
 
 netplan-dbus: src/dbus.c src/_features.h
-        $(CC) $(BUILDFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ $^ `pkg-config --cflags --libs libsystemd glib-2.0`
+	$(CC) $(BUILDFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ $^ `pkg-config --cflags --libs libsystemd glib-2.0`
 
 src/_features.h: src/[^_]*.[hc]
-        printf "#include <stddef.h>\nstatic const char *feature_flags[] __attribute__((__unused__)) = {\n" > $@
-        awk 'match ($$0, /netplan-feature:.*/ ) { $$0=substr($$0, RSTART, RLENGTH); print "\""$$2"\"," }' $^ >> $@
-        echo "NULL, };" >> $@
+	printf "#include <stddef.h>\nstatic const char *feature_flags[] __attribute__((__unused__)) = {\n" > $@
+	awk 'match ($$0, /netplan-feature:.*/ ) { $$0=substr($$0, RSTART, RLENGTH); print "\""$$2"\"," }' $^ >> $@
+	echo "NULL, };" >> $@
 
 netplan/_features.py: src/[^_]*.[hc]
-        echo "# Generated file" > $@
-        echo "NETPLAN_FEATURE_FLAGS = [" >> $@
-        awk 'match ($$0, /netplan-feature:.*/ ) { $$0=substr($$0, RSTART, RLENGTH); print "    \""$$2"\"," }' $^ >> $@
-        echo "]" >> $@
+	echo "# Generated file" > $@
+	echo "NETPLAN_FEATURE_FLAGS = [" >> $@
+	awk 'match ($$0, /netplan-feature:.*/ ) { $$0=substr($$0, RSTART, RLENGTH); print "    \""$$2"\"," }' $^ >> $@
+	echo "]" >> $@
 
 clean:
-        rm -f netplan/_features.py src/_features.h
-        rm -f generate
-        rm -f *.o *.so*
-        rm -f netplan-dbus dbus/*.service
-        rm -f *.gcda *.gcno generate.info
-        rm -rf test-coverage .coverage
+	rm -f netplan/_features.py src/_features.h
+	rm -f generate
+	rm -f *.o *.so*
+	rm -f netplan-dbus dbus/*.service
+	rm -f *.gcda *.gcno generate.info
+	rm -rf test-coverage .coverage
 
 check: default linting
-        tests/cli.py
-        $(NOSETESTS3) -v --with-coverage
+	tests/cli.py
+	$(NOSETESTS3) -v --with-coverage
 
 linting:
-        $(PYFLAKES3) $(PYCODE)
-        $(PYCODESTYLE3) --max-line-length=130 $(PYCODE)
+	$(PYFLAKES3) $(PYCODE)
+	$(PYCODESTYLE3) --max-line-length=130 $(PYCODE)
 
 coverage: | pre-coverage c-coverage python-coverage
 
 pre-coverage:
-        rm -f .coverage
-        $(MAKE) CFLAGS="-g -O0 --coverage" clean check
-        mkdir -p test-coverage/C test-coverage/python
+	rm -f .coverage
+	$(MAKE) CFLAGS="-g -O0 --coverage" clean check
+	mkdir -p test-coverage/C test-coverage/python
 
 check-coverage: coverage
-        @if grep headerCovTableEntryHi test-coverage/C/index.html | grep -qv '100.*%'; then \
-            echo "FAIL: Test coverage not 100%!" >&2; exit 1; \
-        fi
-        python3-coverage report --omit=/usr* --show-missing --fail-under=100
+	@if grep headerCovTableEntryHi test-coverage/C/index.html | grep -qv '100.*%'; then \
+	    echo "FAIL: Test coverage not 100%!" >&2; exit 1; \
+	fi
+	python3-coverage report --omit=/usr* --show-missing --fail-under=100
 
 c-coverage:
-        lcov --directory . --capture --gcov-tool=$(GCOV) -o generate.info
-        lcov --remove generate.info "/usr*" -o generate.info
-        genhtml -o test-coverage/C/ -t "generate test coverage" generate.info
+	lcov --directory . --capture --gcov-tool=$(GCOV) -o generate.info
+	lcov --remove generate.info "/usr*" -o generate.info
+	genhtml -o test-coverage/C/ -t "generate test coverage" generate.info
 
 python-coverage:
-        python3-coverage html -d test-coverage/python --omit=/usr* || true
-        python3-coverage xml --omit=/usr* || true
+	python3-coverage html -d test-coverage/python --omit=/usr* || true
+	python3-coverage xml --omit=/usr* || true
 
 install: default
-        mkdir -p $(DESTDIR)/$(SBINDIR) $(DESTDIR)/$(ROOTLIBEXECDIR)/netplan $(DESTDIR)/$(SYSTEMD_GENERATOR_DIR) $(DESTDIR)/$(LIBDIR)
-        mkdir -p $(DESTDIR)/$(MANDIR)/man5 $(DESTDIR)/$(MANDIR)/man8
-        mkdir -p $(DESTDIR)/$(DOCDIR)/netplan/examples
-        mkdir -p $(DESTDIR)/$(DATADIR)/netplan/netplan
-        mkdir -p $(DESTDIR)/$(INCLUDEDIR)/netplan
-        install -m 755 generate $(DESTDIR)/$(ROOTLIBEXECDIR)/netplan/
-        find netplan/ -name '*.py' -exec install -Dm 644 "{}" "$(DESTDIR)/$(DATADIR)/netplan/{}" \;
-        install -m 755 src/netplan.script $(DESTDIR)/$(DATADIR)/netplan/
-        ln -srf $(DESTDIR)/$(DATADIR)/netplan/netplan.script $(DESTDIR)/$(SBINDIR)/netplan
-        ln -srf $(DESTDIR)/$(ROOTLIBEXECDIR)/netplan/generate $(DESTDIR)/$(SYSTEMD_GENERATOR_DIR)/netplan
-        # lib
-        install -m 644 *.so.* $(DESTDIR)/$(LIBDIR)/
-        ln -snf libnetplan.so.$(NETPLAN_SOVER) $(DESTDIR)/$(LIBDIR)/libnetplan.so
-        # headers, dev data
-        install -m 644 src/*.h $(DESTDIR)/$(INCLUDEDIR)/netplan/
-        # TODO: install pkg-config once available
-        # docs, data
-        install -m 644 examples/*.yaml $(DESTDIR)/$(DOCDIR)/netplan/examples/
-        install -T -D -m 644 netplan.completions $(DESTDIR)/$(BASH_COMPLETIONS_DIR)/netplan
-        # dbus
-        mkdir -p $(DESTDIR)/$(DATADIR)/dbus-1/system.d $(DESTDIR)/$(DATADIR)/dbus-1/system-services
-        install -m 755 netplan-dbus $(DESTDIR)/$(ROOTLIBEXECDIR)/netplan/
-        install -m 644 dbus/io.netplan.Netplan.conf $(DESTDIR)/$(DATADIR)/dbus-1/system.d/
-        install -m 644 dbus/io.netplan.Netplan.service $(DESTDIR)/$(DATADIR)/dbus-1/system-services/
+	mkdir -p $(DESTDIR)/$(SBINDIR) $(DESTDIR)/$(ROOTLIBEXECDIR)/netplan $(DESTDIR)/$(SYSTEMD_GENERATOR_DIR) $(DESTDIR)/$(LIBDIR)
+	mkdir -p $(DESTDIR)/$(MANDIR)/man5 $(DESTDIR)/$(MANDIR)/man8
+	mkdir -p $(DESTDIR)/$(DOCDIR)/netplan/examples
+	mkdir -p $(DESTDIR)/$(DATADIR)/netplan/netplan
+	mkdir -p $(DESTDIR)/$(INCLUDEDIR)/netplan
+	install -m 755 generate $(DESTDIR)/$(ROOTLIBEXECDIR)/netplan/
+	find netplan/ -name '*.py' -exec install -Dm 644 "{}" "$(DESTDIR)/$(DATADIR)/netplan/{}" \;
+	install -m 755 src/netplan.script $(DESTDIR)/$(DATADIR)/netplan/
+	ln -srf $(DESTDIR)/$(DATADIR)/netplan/netplan.script $(DESTDIR)/$(SBINDIR)/netplan
+	ln -srf $(DESTDIR)/$(ROOTLIBEXECDIR)/netplan/generate $(DESTDIR)/$(SYSTEMD_GENERATOR_DIR)/netplan
+	# lib
+	install -m 644 *.so.* $(DESTDIR)/$(LIBDIR)/
+	ln -snf libnetplan.so.$(NETPLAN_SOVER) $(DESTDIR)/$(LIBDIR)/libnetplan.so
+	# headers, dev data
+	install -m 644 src/*.h $(DESTDIR)/$(INCLUDEDIR)/netplan/
+	# TODO: install pkg-config once available
+	# docs, data
+	install -m 644 examples/*.yaml $(DESTDIR)/$(DOCDIR)/netplan/examples/
+	install -T -D -m 644 netplan.completions $(DESTDIR)/$(BASH_COMPLETIONS_DIR)/netplan
+	# dbus
+	mkdir -p $(DESTDIR)/$(DATADIR)/dbus-1/system.d $(DESTDIR)/$(DATADIR)/dbus-1/system-services
+	install -m 755 netplan-dbus $(DESTDIR)/$(ROOTLIBEXECDIR)/netplan/
+	install -m 644 dbus/io.netplan.Netplan.conf $(DESTDIR)/$(DATADIR)/dbus-1/system.d/
+	install -m 644 dbus/io.netplan.Netplan.service $(DESTDIR)/$(DATADIR)/dbus-1/system-services/
 
 %.service: %.service.in
-        sed -e "s#@ROOTLIBEXECDIR@#$(ROOTLIBEXECDIR)#" $< > $@
+	sed -e "s#@ROOTLIBEXECDIR@#$(ROOTLIBEXECDIR)#" $< > $@
 
 .PHONY: clean
